language: java
script: mvn clean install -Pengine-integration,webapps-integration,jboss,h2 -am -pl qa/integration-tests-engine,qa/integration-tests-webapps
  -B -U -q -Dsignavio.globaluser=${globaluser} -Dsignavio.globalpassword=${globalpassword} -Dsignavio.baseurl=${baseurl}
jdk:
- oraclejdk7
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  global:
  - secure: g+VLuyoGH05gFiosgt/quTpuwcPUxbFdUQucn4NzNGXjeAMvVp8cl1TUjw3QVh+XRsK4udkCqqu2I+gouNes3/SuBgKsdcWO6TX6zteSr5a+oPpDMUrZ48zHJoAj5AsmV6o56/Khpy0NgbPoxo46W71wWlUAvl+aEkCeO/5mAM0=
  - secure: vPlYFkqxY/h7oqicRAEG7okEhspnjjiKqc5VB5krFwLuroLt1eg9/BewGL7YvBAmLejxcjndl4nDy+5A4s/z3SQSwsX4ICxF9qANjZy6wO31Sfwx1dTip7Stg4yRziUk+IDpaC8iyqQYOxpOVvF7QBhcf95Cto58hnj8kTcIpxM=
  - secure: rY8dcLoKpQJ6R3oIdsNjhrtZm9lmtf47Vt+WvVG+5/uK4vc968tYIcj1yQzMJdIYOBlrrupeYyOLakrY4zwSmXCJKbCAgPo3s3/dpgdmqI2yXTic9/FsOxnb2hVBULf+IdYN153H3O4xivFPu766PuzHMrrpQC2uHm04rCsgs4s=
notifications:
  email:
    - cl@camunda.com