# Data structure:
#
# $matrixId:
#   stages: [LIST; REQUIRED; Doc: defines the stage types to be used in the matrix generation ]
#   databases: [LIST; OPTIONAL; Doc: defines the databases to be used in the stage generation ]
engine-webapp-unit:
  databases:
  - 'azure_sql_db'
  stages: 
  - 'db-unit'
  - 'db-unit-authorizations'
engine-rest:
  stages:
  - 'engine-rest-unit-jersey-2'
  - 'engine-rest-unit-resteasy'
  - 'engine-rest-unit-resteasy3'
  - 'engine-rest-unit-cxf'
  - 'engine-rest-unit-wink'
  - 'engine-rest-unit-jaxrs2-jersey-2'
  - 'engine-rest-unit-jaxrs2-resteasy3'
  - 'engine-rest-unit-compatibility-wildfly'
  - 'engine-rest-IT-embedded-wildfly'
daily-stages:
  databases:
  - 'azure_sql_db'
  stages: 
  - 'sql-scripts'
  - 'upgrade-database'
  - 'instance-migration'
  - 'old-engine'
  - 'rolling-update'
  - 'large-data-tests'
sidetrack-stages:
  databases:
  - 'cockroachdb_201'
  stages:
  - 'db-unit'
  - 'db-unit-authorizations'
  - 'upgrade-database'
  - 'instance-migration'
  - 'old-engine'
  - 'rolling-update'
  - 'large-data-tests'
jdk-ce-stages:
  stages:
  - 'platform-jdk-openjdk-jdk-15-latest'
  - 'platform-jdk-openjdk-jdk-14-latest'
  - 'platform-jdk-openjdk-jdk-13-latest'
  - 'platform-jdk-openjdk-jdk-12-latest'
  - 'platform-jdk-openjdk-jdk-11-latest'
  - 'platform-jdk-openjdk-jdk-8-latest'
  - 'platform-jdk-jdk-15-latest'
  - 'platform-jdk-jdk-14-latest'
  - 'platform-jdk-jdk-13-latest'
  - 'platform-jdk-jdk-12-latest'
  - 'platform-jdk-jdk-11-latest'
  - 'platform-jdk-jdk-8-latest'
  - 'platform-jdk-ibm-jdk-8-latest'
